name: LinkedIn Auto Poster Cron

on:
  schedule:
    - cron: '0 13 * * *'
    - cron: '0 16 * * *'
    - cron: '0 18 * * *'
    - cron: '0 20 * * *'
    - cron: '0 22 * * *'
  workflow_dispatch: # Allows manual triggering from the GitHub UI if needed

jobs:
  run-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger API Endpoint
        run: |
          curl -X POST "${{ secrets.CRON_URL }}" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
          -H "Content-Type: application/json"
